// Short, original lines grouped by time-of-day period.
// Feel free to edit, add your own, or delete ones that don't land for you.

export interface Period {
  key: string;
  label: string;
  start: number; // inclusive hour, 24h format
  end: number; // exclusive hour, 24h format
  icon: string;
}

export const PERIODS: Period[] = [
  { key: 'midnight', label: 'Midnight', start: 0, end: 4, icon: '🌑' },
  { key: 'dawn', label: 'Dawn', start: 4, end: 6, icon: '🌌' },
  { key: 'sunrise', label: 'Sunrise', start: 6, end: 8, icon: '🌅' },
  { key: 'morning', label: 'Morning', start: 8, end: 10, icon: '🌤️' },
  { key: 'forenoon', label: 'Forenoon', start: 10, end: 12, icon: '🌿' },
  { key: 'noon', label: 'Noon', start: 12, end: 13, icon: '☀️' },
  { key: 'afternoon', label: 'Afternoon', start: 13, end: 16, icon: '🌻' },
  { key: 'dusk', label: 'Dusk', start: 16, end: 18, icon: '🌇' },
  { key: 'twilight', label: 'Twilight', start: 18, end: 20, icon: '🌆' },
  { key: 'evening', label: 'Evening', start: 20, end: 22, icon: '🌃' },
  { key: 'night', label: 'Night', start: 22, end: 24, icon: '🌙' },
];

export function getPeriodForHour(hour: number): Period {
  return PERIODS.find((p) => hour >= p.start && hour < p.end) ?? PERIODS[0];
}

export const MESSAGES: Record<string, string[]> = {
  midnight: [
    "Still up? That's fine. You don't have to have it all figured out tonight.",
    "The world is quiet right now, and so can you be. Rest is not weakness.",
    "Whatever today was, it's over. Tomorrow hasn't judged you yet.",
    "You made it through another day. That's not nothing.",
    "Close your eyes if you can. You're allowed to stop for now.",
    "Nobody expects anything from you at this hour. Just breathe.",
    "This dark is temporary — it always turns into morning.",
    "You're not alone in being awake right now, even if it feels that way.",
    "Whatever thought is looping right now, it will look smaller by daylight.",
    "You don't owe the night a solution. Sleep on it if you can.",
    "Somewhere, someone else is awake at this exact hour, feeling not-so-different from you.",
    "This is a good time to put the phone down and just lie still for a minute.",
    "You survived today. You don't have to do anything else right now.",
    "Whatever's replaying in your head, it's allowed to just be background noise tonight.",
    "You're not behind. You're just still up, like a lot of people are.",
    "It's okay if today wasn't good. It's over now.",
    "The hardest hours are often the quiet ones. You're getting through this one too.",
    "You don't have to earn rest. You can just take it.",
    "This moment will pass, like every other 3am has.",
    "Whatever's heavy right now doesn't have to be solved before you sleep.",
    "You're allowed to feel exactly how you feel right now, no editing required.",
    "The house is quiet, your mind is loud — that's a normal kind of hard.",
    "You don't need the perfect thought to fall asleep on. Any thought will do.",
    "Tomorrow gets a fresh shot at things. Tonight just needs you to rest.",
    "You made it to midnight. That's further than some days feel possible.",
    "It's okay to not be okay right now, as long as you're safe.",
    "Whatever kept you up, it doesn't define the whole of you.",
    "You are allowed to stop performing for the day. Nobody's watching now.",
    "This hour has a way of making things feel bigger than they are. Be gentle with yourself.",
    "You're not failing at sleep. Some nights are just like this.",
    "However dark it feels, this isn't the whole story — just one chapter.",
    "You don't have to justify being tired, sad, or wired right now. It just is what it is.",
    "Whatever you're carrying, you can set it down for these next few hours.",
    "You made it through today's hardest parts. Let that be enough for now.",
    "It's fine if your mind won't quiet down yet. It usually does eventually.",
    "You're still someone worth caring about, even at your most exhausted.",
    "This late, being gentle with yourself matters more than being productive.",
    "You don't need to solve your whole life at this hour. Just get through the night.",
    "Whatever tomorrow brings, it starts after you've rested, not before.",
    "You're doing okay, even if okay feels far away right now.",
    "The stillness of night isn't your enemy. Let it hold you for a bit.",
    "You don't have to have answers tonight. Questions can wait for morning.",
    "Whatever you're feeling alone in, plenty of people have felt it at this same hour.",
    "You're not wasting time by resting. Rest is the point right now.",
    "This is just one dark hour in a life that has held plenty of light too.",
    "You made it here, to this exact moment, still trying. That counts.",
    "Whatever's unresolved can stay unresolved until morning. It'll keep.",
    "You don't have to be strong for anyone at this hour. Just be.",
    "The night doesn't need anything from you except to let it pass.",
    "You are still you, even in the hardest, quietest hour of the day.",
  ],
  dawn: [
    "Before anyone else is up, it's just you and a fresh start. Take it slow.",
    "Nothing has gone wrong yet today. That's a good place to begin.",
    "The night held on for you. Now let the light in a little.",
    "You get another try. Not everyone treats that as a gift, but you can.",
    "Small hours, small steps. That's enough for now.",
    "You're still here. That already counts for something.",
    "Whatever yesterday was, this is a new page — blank, and yours.",
    "Quiet mornings like this one are made for gentleness, especially with yourself.",
    "The world hasn't asked anything of you yet. Enjoy this stillness.",
    "You woke up. That's the first win of the day, however small it seems.",
    "This early light is a reminder that things do, in fact, keep changing.",
    "You get to decide what today means, starting from right now.",
    "Nobody's watching yet. This is a good time to just be, without performance.",
    "Whatever's ahead, it hasn't happened yet — you're still just here, safe, breathing.",
    "The quiet before the day starts is a good place to remember you're allowed rest too.",
    "You don't need to have today figured out yet. Just start it.",
    "This hour belongs to you before it belongs to anyone else's expectations.",
    "You made it to another dawn. That's not something to take lightly.",
    "Whatever weighed on you yesterday, it doesn't automatically carry over to today.",
    "The stillness right now is a kind of permission to move slowly.",
    "You're allowed to ease into today instead of launching into it.",
    "This is a good moment to be proud of just getting out of bed.",
    "Today hasn't disappointed you yet. Let that be a small comfort.",
    "You don't need certainty about today to be ready for it.",
    "Whatever's uncertain, you can meet it one hour at a time.",
    "This is the version of today with the least regret in it so far. Notice that.",
    "You're not behind before you've even started. There's no clock on this morning yet.",
    "The dark is loosening its grip a little more each minute. So can whatever's weighing on you.",
    "You get to choose, in this quiet moment, to be a little kinder to yourself today.",
    "Nothing about today is decided yet — that's actually good news.",
    "This early hush is proof that some things arrive gently, without needing to be forced.",
    "You don't have to greet today with enthusiasm. Just greeting it is enough.",
    "Whatever tomorrow needed from you, it's not due yet. Today can be its own thing.",
    "The fact that you're up for this one matters more than how you feel about it.",
    "You're allowed to want today to be different, and to try, without guaranteeing it will be.",
    "This is a good time to remind yourself that most days turn out okay, even the uncertain ones.",
    "Whatever you didn't finish yesterday isn't a verdict on who you are.",
    "You get a blank slate this morning, even if you don't feel ready to use it yet.",
    "This quiet hour is enough of a reason to feel a little hopeful.",
    "You don't need permission to start slow today.",
    "Whatever's been hard lately, this new day doesn't already know that story.",
    "You're allowed to be tired and still show up for this one.",
    "This is a good time to set one small, kind intention for yourself, nothing more.",
    "The world resets a little every morning. So can you.",
    "You don't owe today your best. Just your presence is enough to start.",
    "Whatever's on your mind, it can wait until the sun's fully up.",
    "This is the part of the day where things still feel possible. Hold onto that.",
    "You made it here before most people are even awake. That's its own kind of quiet strength.",
    "Whatever happens later, right now you're just here, and that's okay.",
    "The morning doesn't need you to have a plan yet. It just needs you to breathe.",
  ],
  sunrise: [
    "Something in you got up today. Don't underestimate that.",
    "The sun didn't skip you. Neither should you.",
    "You don't need a reason to deserve a good day — just start it.",
    "One step at a time gets you further than you think.",
    "This is the part of the day nobody can take from you. Enjoy it a little.",
    "You've survived every hard morning so far. This one's no different.",
    "Let today be easier on yourself than yesterday was.",
    "Whatever's ahead, you get to meet it as someone who's still trying. That matters.",
    "The light coming up right now doesn't ask anything of you — just take it in.",
    "You showed up for this day before it even asked you to.",
    "Whatever you're carrying into today, you don't have to carry it alone.",
    "This is a good moment to notice you're still capable of starting fresh.",
    "You don't have to feel ready to be ready enough.",
    "The sky changing right now is proof that things shift, even slowly.",
    "You're allowed to take today one small win at a time.",
    "This early light is a quiet reminder that beginnings are always available.",
    "You're not the same person who struggled yesterday — today's a slightly different you.",
    "Whatever's uncertain about today, you've handled uncertainty before.",
    "This is the kind of morning that doesn't need to be perfect to be good.",
    "You get to decide, right now, that today counts for something.",
    "The world is just waking up with you. You're not behind it.",
    "You don't need motivation to start — just a first small step.",
    "Whatever's weighing on you, the sunrise doesn't make it disappear, but it does make it a little more bearable.",
    "This is a good time to remember that most hard things get easier once you're moving.",
    "You've made it through every sunrise so far. That's not a small thing.",
    "Today doesn't need to be your best day. It just needs to be a day you got through with some care for yourself.",
    "The light stretching out right now is patient with you. Try to be too.",
    "You don't have to feel inspired to still show up.",
    "Whatever's on today's list, it doesn't define your worth either way.",
    "This is a good moment to take one slow breath before the day picks up speed.",
    "You're allowed to start today quietly, without announcing anything to anyone.",
    "The sun rising doesn't rush — it just steadily gets brighter. You can move at your own pace too.",
    "You don't need yesterday's energy to make it through today.",
    "This early hour is proof that even hard stretches eventually give way to light.",
    "You get to choose, again, to try. That's worth acknowledging.",
    "Whatever's nervous in you about today, it's allowed to come along — it doesn't have to lead.",
    "This is a good time to remember: not every day has to be a big one to matter.",
    "You showed up for another one. However today goes, that's already something.",
    "The horizon changing color is a small, steady kind of hope. Let it be enough for now.",
    "You don't need to have your whole day planned to take the first step of it.",
    "Whatever's ahead, you're allowed to meet it tired, uncertain, or unsure — just meet it.",
    "This is a good moment to be a little proud of simply beginning.",
    "You're not required to feel good about today to still get through it.",
    "The light is coming up regardless of how you feel about it — and so can you.",
    "You don't have to chase a good day. Sometimes it just needs you to start it gently.",
    "Whatever's uncertain right now, it usually looks different by midday.",
    "This early quiet is a good place to remind yourself you're allowed to go easy today.",
    "You made it to another beginning. However small that feels, it's real.",
    "The sunrise doesn't care what yesterday looked like. Maybe you can let today have the same freedom.",
    "You're allowed to greet today without pressure to feel anything specific about it.",
  ],
  morning: [
    "You're allowed to have an ordinary day. Not every day needs to be a triumph.",
    "Whatever's on your list, you don't have to do it perfectly — just do it.",
    "You've handled harder mornings than this one.",
    "A little progress today is still progress.",
    "You're doing better than you're giving yourself credit for.",
    "It's okay to go slow, as long as you keep going.",
    "Someone out there is glad you exist, even if they haven't said it lately.",
    "This morning doesn't have to fix everything. It just has to happen.",
    "You don't have to feel motivated to still get things done.",
    "Whatever's hard about today, you're allowed to take it one task at a time.",
    "You're not required to be at your best every morning. Showing up counts too.",
    "This is a good time to be honest with yourself about what you actually need today.",
    "You've gotten through every difficult morning that's come before this one.",
    "Whatever's on your mind, it doesn't have to be resolved before you start your day.",
    "You're allowed to move at a pace that actually works for you, not someone else's.",
    "This morning is just one part of a much longer story you're still writing.",
    "You don't have to prove anything to yourself today. Just get through it kindly.",
    "Whatever mistakes happened yesterday, this morning doesn't inherit them automatically.",
    "You're doing more than you think, even on the days that feel unremarkable.",
    "This is a good time to remind yourself that rest and effort aren't opposites.",
    "You don't need a perfect morning routine to have a decent day.",
    "Whatever's stressing you, it will likely look different by this afternoon.",
    "You're allowed to start slow and pick up speed later, or not at all.",
    "This morning doesn't need to be productive to be worthwhile.",
    "You've made it through worse mornings than this, even if you don't remember all of them.",
    "Whatever's undone from yesterday, you can pick it back up without shame.",
    "You're not behind — you're exactly where today needs you to start from.",
    "This is a good moment to be a little easier on yourself than usual.",
    "You don't have to feel capable to still be capable.",
    "Whatever's uncertain about today, you can figure it out as you go.",
    "You're allowed to need a slow start. Not everyone runs at full speed by 9am.",
    "This morning, being kind to yourself matters more than being efficient.",
    "You've survived every version of today that's come before. You'll survive this one too.",
    "Whatever's weighing on you, it doesn't get to run the whole day.",
    "You're doing fine, even if fine doesn't feel like much right now.",
    "This is a good time to remember that not every morning needs a plan.",
    "You don't owe today enthusiasm you don't have. Just effort is enough.",
    "Whatever's on your plate, you're allowed to take it in pieces.",
    "You're capable of more than this particular morning is letting you feel.",
    "This is a good moment to notice: you got up, and that's already something.",
    "You don't have to have your whole day sorted to take the next step of it.",
    "Whatever's frustrating about this morning, it's temporary, even if it doesn't feel that way.",
    "You're allowed to be tired and still be doing okay.",
    "This is a good time to remind yourself that ordinary days add up to a good life too.",
    "You don't need a burst of motivation. Small, steady effort works fine.",
    "Whatever's hard right now, you've gotten through hard mornings before.",
    "You're not required to love your morning to get through it well.",
    "This is a good moment to just take the next small step, not the whole day at once.",
    "You're doing okay, even on the mornings that don't feel like much.",
    "Whatever today asks of you, you're allowed to answer it at your own pace.",
  ],
  forenoon: [
    "You're halfway to noon and still standing. That's real.",
    "Take the small win when it shows up — you earned it.",
    "You don't owe anyone constant productivity to be worth something.",
    "If today feels heavy, carrying it one hour at a time is enough.",
    "You've made it through tougher stretches than this.",
    "It's fine to pause. The list will still be there in five minutes.",
    "You're more capable than the voice in your head gives you credit for.",
    "Drink some water, breathe, and give yourself a break — you're doing fine.",
    "This stretch of the morning is often the grind — you're allowed to feel it.",
    "You don't have to finish everything by noon to consider today a success.",
    "Whatever's slow-going right now, slow still counts as moving.",
    "You're doing more than you're noticing, buried in the middle of a task.",
    "This is a good time to check in with yourself — are you okay, actually?",
    "You don't need to sprint through the rest of the morning. Steady is fine.",
    "Whatever's frustrating you right now, it's a moment, not the whole morning.",
    "You've handled this kind of mid-morning slump before and gotten through it.",
    "This is a good time to remember effort doesn't have to look impressive to matter.",
    "You're allowed to feel behind and still be doing okay.",
    "Whatever's on your plate right now, you can take it one piece at a time.",
    "You don't have to earn a break — take one if you need it.",
    "This part of the day can be a slog, and that doesn't mean you're doing it wrong.",
    "You're more resilient than this particular hard hour is giving you credit for.",
    "Whatever's stalling you right now, it's okay to just sit with it for a minute.",
    "You've gotten through harder late-mornings than this one.",
    "This is a good time to remind yourself that rest mid-task isn't a failure.",
    "You don't need to have accomplished everything by now to be doing fine.",
    "Whatever's dragging on you right now, it will not last the whole day.",
    "You're allowed to feel tired mid-morning without that meaning you're failing.",
    "This is a good time to lower the bar a little, if you need to.",
    "You've made it this far into the day, and that's not nothing.",
    "Whatever's stressing you, breaking it into smaller steps usually helps.",
    "You don't have to push through everything at full strength.",
    "This stretch of the day rewards patience with yourself more than speed.",
    "You're doing okay, even if the middle of the morning feels like a grind.",
    "Whatever's unresolved right now can probably wait a little longer.",
    "You've earned a proper break today, even if you haven't taken one yet.",
    "This is a good time to notice what's actually working, not just what isn't.",
    "You don't need to feel energized to keep gently moving forward.",
    "Whatever's hard about this part of the day, you're handling it better than it feels.",
    "You're allowed to slow way down right now if that's what you need.",
    "This mid-morning stretch doesn't define the whole day's outcome.",
    "You've survived every forenoon that's felt this long before.",
    "Whatever's weighing on your focus, it's okay to acknowledge it and keep going anyway.",
    "You don't have to be at full capacity every single hour.",
    "This is a good time to remember that consistency beats intensity most days.",
    "You're doing better than the tiredness in your body is telling you.",
    "Whatever's frustrating about today so far, noon is close, and it usually resets things a little.",
    "You've made real progress today, even the parts that don't feel like much.",
    "This is a good moment to be gentle with your own pace.",
    "You don't need to have it all together by midday. Just keep going, gently.",
  ],
  noon: [
    "You're right in the middle of your day. Take a beat before you push through.",
    "Eat something. Rest a second. You've earned it just by getting here.",
    "Halfway through, still standing — that's worth noticing.",
    "You don't have to have this all figured out by tonight.",
    "This is a good moment to remind yourself: you matter, not just what you produce.",
    "The rest of today can be lighter than the first half.",
    "You're allowed to feel proud of getting through the morning.",
    "Whatever's stressing you right now, it will not feel this big by tomorrow.",
    "This is a good time to step away from whatever you're doing, even for five minutes.",
    "You've made it to the middle of the day — that alone is worth a small pause.",
    "Whatever the morning was like, this moment is a clean reset point.",
    "You don't need to have a plan for the afternoon yet. Just breathe first.",
    "This is a good time to notice how your body feels, not just your to-do list.",
    "You're allowed to eat lunch without multitasking through it.",
    "Whatever's unresolved from the morning can wait until after this break.",
    "This midday pause matters more than it seems like it does.",
    "You don't have to justify taking a real break right now.",
    "Whatever's hard about today so far, you're allowed to set it down for a bit.",
    "This is a good moment to drink some water and just exist for a second.",
    "You've earned this pause, whether or not the morning went the way you wanted.",
    "Whatever's next, it can wait a few more minutes while you actually rest.",
    "This is a good time to remember that the afternoon gets its own fresh chance.",
    "You don't owe the rest of the day your full intensity right away.",
    "Whatever's weighing on you at noon, it usually feels lighter by evening.",
    "This is a good moment to check in — are you hungry, tired, overwhelmed? All are valid.",
    "You're allowed to slow the whole day down right now if you need to.",
    "Whatever's stressing you, it will still be there in ten minutes — take the ten minutes anyway.",
    "This is a good time to remember you're a person, not just a schedule.",
    "You don't have to have accomplished a certain amount by now to deserve lunch.",
    "Whatever's frustrating about today, noon is a natural place to let some of it go.",
    "This is a good moment to just sit still for a second, without a task attached.",
    "You've made it halfway. However the second half goes, that matters too.",
    "Whatever's on your mind, it's allowed to quiet down for the length of a meal.",
    "This is a good time to be kind to your body — it's been working all morning.",
    "You don't need permission to take a real lunch break. Take it anyway.",
    "Whatever's unresolved can resume after this pause. It's not going anywhere.",
    "This midday light is a good reminder that the day is still wide open.",
    "You're allowed to reset your mood right now, regardless of how the morning went.",
    "Whatever's heavy, it's okay to set it on the table next to your lunch for a minute.",
    "This is a good time to notice: you're still here, still trying, still okay.",
    "You don't have to rush back into things the second you're done eating.",
    "Whatever's next on your list, it will still be there after you've actually rested.",
    "This is a good moment to remember that pacing yourself is a skill, not a weakness.",
    "You've earned a few minutes of doing absolutely nothing, if you can find them.",
    "Whatever's stressing you about the afternoon, it hasn't happened yet.",
    "This is a good time to just be a person eating lunch, nothing more required.",
    "You don't need the morning to have gone perfectly to have a good afternoon.",
    "Whatever's on your mind, it's allowed to sit quietly while you eat.",
    "This is a good moment to remind yourself that midday check-ins matter.",
    "You're allowed to treat this pause as more than just a formality.",
  ],
  afternoon: [
    "Energy dipping? That's human, not failure.",
    "You don't have to finish strong — you just have to finish.",
    "This part of the day is often the hardest. You're handling it.",
    "A short break isn't quitting, it's maintenance.",
    "You're allowed to be tired and still be doing okay.",
    "Whatever's frustrating you right now is a moment, not your whole story.",
    "You've gotten through every difficult afternoon before this one.",
    "Be as patient with yourself as you'd be with someone you love.",
    "This slump is common enough that it has a name for a reason. You're not uniquely failing.",
    "You don't need a burst of energy to keep gently going.",
    "Whatever's dragging on you, a short walk or a glass of water sometimes actually helps.",
    "This is a good time to lower your expectations for yourself a little, on purpose.",
    "You're allowed to coast for a bit if that's what you have in you right now.",
    "Whatever's stalling, it doesn't mean the whole day is a wash.",
    "This part of the afternoon rewards patience more than force.",
    "You don't have to push through everything at full intensity.",
    "Whatever's hard right now, it's temporary — the day does eventually end.",
    "This is a good time to remember that tired isn't the same as failing.",
    "You've handled this exact kind of afternoon slump before.",
    "Whatever's weighing on your focus, it's okay to just acknowledge it and keep going slowly.",
    "This is a good moment to be gentle about how much you're actually capable of right now.",
    "You don't need to match the morning's energy to still be doing fine.",
    "Whatever's frustrating you, most of it will feel smaller by evening.",
    "This is a good time to take a real break, not just switch tasks.",
    "You're allowed to admit today has been a lot, even if nothing dramatic happened.",
    "Whatever's dragging, you're still moving, and that matters.",
    "This is a good moment to remind yourself rest is productive too, in its own way.",
    "You don't have to feel motivated to still be doing the right things.",
    "Whatever's hard about this stretch, it's a normal part of most days, not a personal failing.",
    "This is a good time to check whether you've eaten or had water recently.",
    "You're allowed to slow down significantly right now if you need to.",
    "Whatever's on your mind, it's okay if it's louder than usual this afternoon.",
    "This is a good moment to be proud of getting this far into the day at all.",
    "You don't need this afternoon to be your best one. Just get through it kindly.",
    "Whatever's frustrating, you can set it aside for a few minutes without consequence.",
    "This is a good time to remember that most people struggle with this exact hour too.",
    "You're allowed to feel done before the day is actually done.",
    "Whatever's dragging you down, it usually eases once you take a real pause.",
    "This is a good moment to notice you've made it through a lot already today.",
    "You don't have to explain or justify needing a break right now.",
    "Whatever's hard, you're handling it, even if it doesn't feel like handling.",
    "This is a good time to be kind about your limits rather than fighting them.",
    "You're allowed to finish the day imperfectly and still call it a win.",
    "Whatever's weighing on you, the evening usually brings a different kind of energy.",
    "This is a good moment to remember effort counts even when it's slow and tired.",
    "You don't need to feel strong right now to actually be handling things.",
    "Whatever's frustrating about today, it doesn't erase what you've already gotten through.",
    "This is a good time to just keep going, however slowly that looks.",
    "You're allowed to be exactly this tired and still be doing enough.",
    "Whatever's left of today, you can meet it at whatever pace you have left in you.",
  ],
  dusk: [
    "The day's winding down — so can you.",
    "However today went, you're still here to see it end. That's worth something.",
    "Let yourself off the hook for whatever didn't go perfectly today.",
    "The sky changes colors right now like it's reminding you things shift. So will this mood.",
    "You don't need a perfect day behind you to deserve a peaceful evening.",
    "This is a good time to breathe out everything you were carrying since morning.",
    "You made it through another one. However messy, it counts.",
    "Whatever's weighing on you, it's allowed to wait until tomorrow.",
    "This changing light is a good reminder that even hard days end.",
    "You don't have to review the whole day to know you got through it.",
    "Whatever went wrong today, it doesn't cancel out what went right.",
    "This is a good time to let your shoulders drop a little, literally.",
    "You're allowed to close out today without a tidy conclusion.",
    "Whatever's unfinished can stay unfinished until tomorrow. It'll keep.",
    "This is a good moment to notice the day is genuinely almost over now.",
    "You don't need to have accomplished everything to deserve to rest tonight.",
    "Whatever's heavy from today, dusk is a good time to start setting it down.",
    "This is a good time to remember today doesn't need to be graded.",
    "You made it through, and that's the whole assignment on hard days.",
    "Whatever's still unresolved, it's allowed to sit overnight without urgency.",
    "This is a good moment to be soft with yourself about how today actually went.",
    "You don't have to carry today's frustrations into tonight.",
    "Whatever's weighing on you, the day changing color right now is a small permission to let it go a little.",
    "This is a good time to notice: however hard, you kept going.",
    "You're allowed to feel relieved that today is nearly done.",
    "Whatever mistakes happened, they belong to today, not to all of your days.",
    "This is a good moment to appreciate just making it to the evening.",
    "You don't need today's ending to be dramatic to be meaningful.",
    "Whatever's on your mind, it can quiet down a little as the light does.",
    "This is a good time to remember that most days, even hard ones, eventually pass.",
    "You made it through whatever today asked of you. That's enough for now.",
    "Whatever's unresolved tonight, tomorrow gets its own fresh attempt at it.",
    "This is a good moment to let go of whatever version of today you were hoping for.",
    "You're allowed to close today out feeling tired, and that's okay.",
    "Whatever's weighing on you, this changing light is a reminder that nothing stays the same for long.",
    "This is a good time to be proud of finishing today, however it went.",
    "You don't have to have today figured out to let it end.",
    "Whatever's hard right now, the evening usually softens it a little.",
    "This is a good moment to notice you're still standing, at the end of it all.",
    "You made it here, to the end of another one. However it went, it's yours.",
    "Whatever's unresolved, it's allowed to stay that way for tonight.",
    "This is a good time to remember today's hard parts don't define your whole story.",
    "You're allowed to let today be over now, imperfections and all.",
    "Whatever's weighing on you, dusk is a good hour to start putting it down.",
    "This is a good moment to breathe a little easier, knowing today's almost done.",
    "You made it through today. That's genuinely enough, even on the hard ones.",
    "Whatever's unfinished, it's not a failure — it's just tomorrow's task now.",
    "This is a good time to soften toward yourself, whatever today looked like.",
    "You're allowed to feel done, tired, and still proud of getting here.",
    "Whatever today held, you carried it. That's worth acknowledging before it ends.",
  ],
  twilight: [
    "The noise of the day is fading. Let some of yours fade with it.",
    "You don't have to solve everything before you rest tonight.",
    "It's okay if today wasn't your best. Tomorrow's not written yet.",
    "You're doing better than the hardest moment of your day made it feel.",
    "This is a good time to be gentle with yourself — you've been carrying a lot.",
    "Whatever's unresolved can stay that way for one more night. You're still okay.",
    "You showed up today. That's the whole assignment, some days.",
    "Let the evening be soft, even if the day wasn't.",
    "This in-between hour is a good time to just exhale.",
    "You don't need today's problems solved before you allow yourself to unwind.",
    "Whatever's lingering from today, it's allowed to lose some of its weight by now.",
    "This is a good time to notice the quiet settling in, and let it settle in you too.",
    "You're allowed to stop trying so hard for the rest of the night.",
    "Whatever's on your mind, it can wait until you've had a proper rest.",
    "This is a good moment to remember that winding down is its own kind of productive.",
    "You don't have to keep performing capability right now. It's okay to just be tired.",
    "Whatever today asked of you, you gave it what you had. That's enough.",
    "This is a good time to let your thoughts slow down along with the light.",
    "You're allowed to feel everything you felt today without needing to fix it tonight.",
    "Whatever's unresolved, it will still be there tomorrow, calmer, probably smaller.",
    "This is a good moment to be proud of getting through today's hardest parts.",
    "You don't need a clear head right now. A tired one is allowed too.",
    "Whatever's weighing on you, twilight is a good hour to start loosening its grip.",
    "This is a good time to remember that not every day needs closure to be over.",
    "You're allowed to let go of today's expectations, met or not.",
    "Whatever's still bothering you, it's okay to set it down for the evening.",
    "This is a good moment to notice how far you've come since this morning.",
    "You don't have to carry today's stress into tomorrow.",
    "Whatever's unresolved, you can pick it back up with a clearer head later.",
    "This is a good time to just sit with the quiet for a minute, no agenda.",
    "You're allowed to feel done for the day, even if the day isn't technically over.",
    "Whatever today held, you're allowed to let the evening feel different from it.",
    "This is a good moment to remember that softness at the end of the day is earned, not given.",
    "You don't need to review today to know you got through it.",
    "Whatever's heavy, this hour is a gentle invitation to set some of it down.",
    "This is a good time to notice you made it here, tired but here.",
    "You're allowed to want nothing more right now than quiet.",
    "Whatever's unresolved in your head, it's allowed to just sit there for now.",
    "This is a good moment to be kind to yourself about how today actually felt.",
    "You don't have to have today sorted out before you rest.",
    "Whatever's lingering, it usually feels lighter after a proper night's sleep.",
    "This is a good time to remember that today doesn't need a neat ending.",
    "You're allowed to let the day just fade out, without a big finish.",
    "Whatever's weighing on you, it's allowed to wait for tomorrow's version of you to handle it.",
    "This is a good moment to notice the day softening, and let yourself soften too.",
    "You don't need anything else from yourself tonight except rest.",
    "Whatever today was, this quiet hour is a good place to release some of it.",
    "This is a good time to be proud, simply, of getting through another one.",
    "You're allowed to stop reaching for anything else today. This is enough.",
    "Whatever's unresolved, you're allowed to trust that you'll handle it when it's time.",
  ],
  evening: [
    "You made it to the end of the day. That's not automatic — you did that.",
    "Whatever you're feeling right now is allowed to just be felt, no fixing required.",
    "You don't have to be okay all the time to be okay overall.",
    "This is your time now — take it back from whatever took up your day.",
    "You're worth more than today's hardest hour suggested.",
    "It's fine to just exist for a while tonight. No agenda needed.",
    "However today went, you're still someone worth showing up for tomorrow.",
    "You're allowed to rest without earning it first.",
    "This is a good time to do something just because you want to, not because it's useful.",
    "You don't owe the evening productivity. It can just be yours.",
    "Whatever today asked of you, you gave what you had. That's genuinely enough.",
    "This is a good moment to check in with yourself, honestly, without judgment.",
    "You're allowed to feel proud of small things — getting through today is one of them.",
    "Whatever's still on your mind, it's okay if it takes a while to quiet down.",
    "This is a good time to be kind to your body — it carried you through today.",
    "You don't have to have a perfect evening routine. Just resting counts.",
    "Whatever went sideways today, tonight is a separate thing from it.",
    "This is a good moment to remember you're allowed to enjoy things, not just endure them.",
    "You're allowed to want comfort tonight, and to go get some.",
    "Whatever's unresolved, it's not your job to solve it this evening.",
    "This is a good time to notice: you're still here, and that matters.",
    "You don't need today to have gone well to deserve a good evening.",
    "Whatever's weighing on you, it's allowed to sit quietly in the background tonight.",
    "This is a good moment to do one small thing that feels good, just because.",
    "You're allowed to let today go, even the parts that still sting a little.",
    "Whatever tomorrow holds, it's not tonight's problem yet.",
    "This is a good time to remember rest isn't something you have to justify.",
    "You don't have to process everything that happened today right now.",
    "Whatever's on your mind, it can wait for a clearer, calmer moment.",
    "This is a good moment to be proud of yourself, plainly, without qualifications.",
    "You're allowed to spend tonight however feels right, not however feels productive.",
    "Whatever's unresolved, tomorrow gets a fresh shot at it.",
    "This is a good time to let yourself feel whatever the day left behind.",
    "You don't need permission to take the rest of tonight easy.",
    "Whatever's heavy, this is a good hour to set some of it down.",
    "This is a good moment to remember: today's over now, mostly, and that's okay.",
    "You're allowed to close today out feeling however you actually feel.",
    "Whatever today asked of you, you're allowed to be done answering for now.",
    "This is a good time to do something gentle for yourself, even something small.",
    "You don't have to have today's meaning figured out yet.",
    "Whatever's unresolved, it's allowed to stay that way until you're ready.",
    "This is a good moment to notice the quiet, and let it be restful rather than lonely.",
    "You're allowed to want nothing more from tonight than rest.",
    "Whatever happened today, you're still someone worth being gentle with.",
    "This is a good time to remember that today's hard parts don't cancel out your worth.",
    "You don't need a reason to treat yourself kindly tonight.",
    "Whatever's on your mind, it's okay if it's still loud right now. It'll quiet down.",
    "This is a good moment to be thankful, simply, that today is almost done.",
    "You're allowed to let tonight be soft, slow, and entirely your own.",
    "Whatever today held, you got through it. That's the whole point of today.",
  ],
  night: [
    "You got through today. However it went, that's the truth of it — you got through it.",
    "If tonight feels heavy, it's okay to just wait it out. Feelings pass, even the big ones.",
    "You are not a burden for struggling. You're a person, and people struggle sometimes.",
    "Whatever's on your mind, it will look different in daylight. Try to let tonight be quiet.",
    "You don't have to carry tomorrow's worries tonight too.",
    "If no one's told you today: you matter, and this specific moment doesn't get to decide your whole story.",
    "Rest now. You're allowed to stop trying to hold everything together for a few hours.",
    "You're still here. After everything, you're still here — and that's worth being gentle with yourself about.",
    "Whatever tonight feels like, it's not permanent, even when it feels that way.",
    "You don't have to have today make sense before you sleep.",
    "This is a good time to remind yourself that surviving hard days is its own quiet kind of strength.",
    "Whatever's weighing on you, you don't have to face it completely alone.",
    "You're allowed to feel exactly as tired, sad, or worn out as you actually are right now.",
    "This late, it's okay if your only goal is to just get some rest.",
    "Whatever happened today, it doesn't get the final say on who you are.",
    "You've made it through every hard night before this one, somehow.",
    "This is a good time to remember that asking for help isn't weakness, it's just honest.",
    "Whatever's looping in your mind, it's allowed to just be noise for tonight.",
    "You matter beyond what you produced or accomplished today.",
    "This is a good moment to be as kind to yourself as you'd be to someone you love who was struggling.",
    "Whatever tonight brings, you don't have to handle it perfectly, just get through it.",
    "You're not alone in finding some nights harder than others.",
    "This is a good time to remind yourself: this feeling, however big, is not the whole truth of your life.",
    "Whatever's heavy right now, it's okay to just sit with it instead of fighting it.",
    "You've been through hard nights before and made it to morning. That matters.",
    "This is a good moment to remember that reaching out to someone is always allowed.",
    "Whatever's on your mind, it doesn't have to be resolved before you can rest.",
    "You're allowed to not be okay tonight, as long as you're safe.",
    "This is a good time to be gentle with the version of you that's struggling right now.",
    "Whatever tonight feels like, you don't have to carry it entirely by yourself.",
    "You matter, plainly and without conditions, even on the hardest nights.",
    "This is a good moment to remember that things can get better, even when it's hard to believe that right now.",
    "Whatever's weighing on you, it's okay to let someone else help carry it.",
    "You've survived one hundred percent of your hardest nights so far.",
    "This is a good time to remind yourself that this moment is not forever, even if it feels endless.",
    "Whatever tonight holds, you're still worth taking care of.",
    "You're allowed to need support, and to actually ask for it.",
    "This is a good moment to remember that you are not alone in this, even when it feels that way.",
    "Whatever's hard right now, reaching out to someone you trust is a strong thing to do, not a weak one.",
    "You matter more than tonight's hardest thought is telling you.",
    "This is a good time to be patient with yourself, exactly as you are right now.",
    "Whatever tonight feels like, it's allowed to just be gotten through, nothing more required.",
    "You've made it through every version of hard that's come before this. You're still here.",
    "This is a good moment to remember that talking to someone can lighten what feels unbearable alone.",
    "Whatever's weighing on you, your life has value that this moment doesn't get to erase.",
    "You're allowed to rest, even with things unresolved. Tomorrow can hold the rest.",
    "This is a good time to remember that hard nights end, even the ones that feel like they won't.",
    "Whatever tonight brings, you deserve care, including from yourself.",
    "You matter. Not for what you do, but simply because you're here.",
    "This is a good moment to be gentle, patient, and a little hopeful with yourself, even now.",
  ],
};

export function getRandomMessage(periodKey: string, excludeMsg?: string): string {
  const pool = MESSAGES[periodKey] ?? MESSAGES.night;
  if (pool.length === 1) return pool[0];
  let choice: string;
  do {
    choice = pool[Math.floor(Math.random() * pool.length)];
  } while (choice === excludeMsg);
  return choice;
}